#wt.secret= "m/yAHo/raAW+n4ufewTG1tw42JVLces6g+UASfDmp5s634jGCK/dv868wemJ6L2p3LNOMxaosC4SaJJ8nD/8cg=="
#jwt.expiration=86400000
spring.jpa.hibernate.ddl-auto=update
spring.application.name=auth
spring.datasource.url=jdbc:mysql://localhost:3306/securityDB
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver